public with sharing class participantListViewModel {
	
	public String id {get;set;}
	public String lastName {get;set;}
	public String firstName {get;set;}
	public String middleName {get;set;}
	public String suffix {get;set;}
	public String birthdate {get;set;}
	public String sex {get;set;}
	public String mailingStreet {get;set;}
	public String mailingStreet2 {get;set;}
	public String mailingCity {get;set;}
	public String mailingState {get;set;}
	public String mailingPostalCode {get;set;}
	public String mailingCountry {get;set;}
	public String phone {get;set;}
	public String homeInstitutionName {get;set;}
	public String homeInstitutionCode {get;set;}
	public String pName {get;set;}
	public String ptName {get;set;}
	public String ptSection {get;set;}
	public String ptYear {get;set;}

	public participantListViewModel(){

	}

}