/**
 * scheduledApplicationStatusEmailTest - Depreciated
 * Test for scheduledApplicationStatusEmail
 * 
 * @author Brock Barlow
 */
@isTest
private class scheduledApplicationStatusEmailTest {
	/*
	private static Map<String, SObject> testData = new Map<String, SObject>();
	
    public static testMethod void testLogic() 
    {    	
    	if(testData == new Map<String, SObject>())
    	{
    		testData = apexMockDataUtility.createIfsaDataCollection();	
    	}
    	Test.startTest();
		scheduledApplicationStatusEmail.sendStatus();
		Test.stopTest();		
    }
    
    public static testMethod void testSchedule()
    {
    	if(testData == new Map<String, SObject>())
    	{
    		testData = apexMockDataUtility.createIfsaDataCollection();	
    	}        
    	Test.startTest();
    	String jobId = System.schedule('testScheduledApplicationStatusEmail',
            '0 0 0 * * ? *', new scheduledApplicationStatusEmail());
        
        Test.stopTest();
    }
	*/
}