/**
* @description Viewmodel for SP_Home page
* @author Cameron Ames
*/
public without sharing class studentHomeViewModel extends studentBaseViewModel
{
    /*
	public String advisorFirstName {get;set;}
    public String advisorLastName {get;set;}
    public String advisorEmail {get;set;}
    public String advisorPhone {get;set;}
    public String advisorPhotoUrl {get;set;}
    public String advisorCalendlyLink {get;set;}
    public String paIntroVideo {get;set;}
    */
}