@isTest
private class studentOnSiteCourseRegViewModelTest 
{

    // Run tests
    @isTest static void test1()
    {
        // Create studentOnSiteCourseRegViewModel instance
        studentOnSiteCourseRegViewModel courseRegVM = new studentOnSiteCourseRegViewModel();

        courseRegVM.applicationID = null;
        courseRegVM.courseCode = null;
		courseRegVM.courseRegId = null;
        courseRegVM.courseId = null;
		courseRegVM.hostInstitutionGrade = null;
        courseRegVM.courseGrade = null;
        courseRegVM.courseName = null;
        courseRegVM.encodedCourseName = null;
        courseRegVM.courseTitle = null;
        courseRegVM.encodedCourseTitle = null;
        courseRegVM.untranslatedTitle = null;
        courseRegVM.alternateFor = null;
        courseRegVM.courseTerm = null;
    	courseRegVM.credits = null;
        courseRegVM.usCreditsEarned = null;
        courseRegVM.selectedDepartment = null;
        courseRegVM.departmentCode = null;
        courseRegVM.departmentCodeString = null;
        courseRegVM.instructorName = null;
        courseRegVM.instructorFirstName = null; 
        courseRegVM.instructorLastName = null;
    	courseRegVM.usCredits = null;
    	courseRegVM.hostInstitutionName = null;
    	courseRegVM.hostInstitutionId = null;
		courseRegVM.originalHostInstitutionName = null;
        courseRegVM.locationId = null;
        courseRegVM.rank = null;
    	courseRegVM.isApproved = null;
    	courseRegVM.isDropped = null;
    	courseRegVM.courseStatus = null;
    	courseRegVM.qualityPoints = null;
        courseRegVM.notRegisteredReason = null;
        courseRegVM.notRegisteredReasonOther = null;
        courseRegVM.otherClassReason = null;
        courseRegVM.otherClassReasonOther = null;
        courseRegVM.fulfillsDegreeRequirement = null;
        courseRegVM.required = null;
    }
}